// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy
{
    public static class GetGitCredentials
    {
        /// <summary>
        /// Use this data source to retrieve information about Git credentials in Octopus Deploy.
        /// </summary>
        public static Task<GetGitCredentialsResult> InvokeAsync(GetGitCredentialsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetGitCredentialsResult>("octopusdeploy:index/getGitCredentials:getGitCredentials", args ?? new GetGitCredentialsArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to retrieve information about Git credentials in Octopus Deploy.
        /// </summary>
        public static Output<GetGitCredentialsResult> Invoke(GetGitCredentialsInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetGitCredentialsResult>("octopusdeploy:index/getGitCredentials:getGitCredentials", args ?? new GetGitCredentialsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetGitCredentialsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the Git Credential to filter by.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// The number of records to skip.
        /// </summary>
        [Input("skip")]
        public int? Skip { get; set; }

        /// <summary>
        /// The space ID associated with this Git Credential.
        /// </summary>
        [Input("spaceId")]
        public string? SpaceId { get; set; }

        /// <summary>
        /// The number of records to take.
        /// </summary>
        [Input("take")]
        public int? Take { get; set; }

        public GetGitCredentialsArgs()
        {
        }
        public static new GetGitCredentialsArgs Empty => new GetGitCredentialsArgs();
    }

    public sealed class GetGitCredentialsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the Git Credential to filter by.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The number of records to skip.
        /// </summary>
        [Input("skip")]
        public Input<int>? Skip { get; set; }

        /// <summary>
        /// The space ID associated with this Git Credential.
        /// </summary>
        [Input("spaceId")]
        public Input<string>? SpaceId { get; set; }

        /// <summary>
        /// The number of records to take.
        /// </summary>
        [Input("take")]
        public Input<int>? Take { get; set; }

        public GetGitCredentialsInvokeArgs()
        {
        }
        public static new GetGitCredentialsInvokeArgs Empty => new GetGitCredentialsInvokeArgs();
    }


    [OutputType]
    public sealed class GetGitCredentialsResult
    {
        /// <summary>
        /// Provides information about existing GitCredentials.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetGitCredentialsGitCredentialResult> GitCredentials;
        /// <summary>
        /// The unique ID for this resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the Git Credential to filter by.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The number of records to skip.
        /// </summary>
        public readonly int? Skip;
        /// <summary>
        /// The space ID associated with this Git Credential.
        /// </summary>
        public readonly string? SpaceId;
        /// <summary>
        /// The number of records to take.
        /// </summary>
        public readonly int? Take;

        [OutputConstructor]
        private GetGitCredentialsResult(
            ImmutableArray<Outputs.GetGitCredentialsGitCredentialResult> gitCredentials,

            string id,

            string? name,

            int? skip,

            string? spaceId,

            int? take)
        {
            GitCredentials = gitCredentials;
            Id = id;
            Name = name;
            Skip = skip;
            SpaceId = spaceId;
            Take = take;
        }
    }
}
