# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .artifactory_generic_feed import *
from .aws_elastic_container_registry import *
from .docker_container_registry import *
from .environment import *
from .get_environments import *
from .get_feeds import *
from .get_git_credentials import *
from .get_library_variable_sets import *
from .get_lifecycles import *
from .get_project_groups import *
from .get_projects import *
from .get_script_modules import *
from .get_space import *
from .get_spaces import *
from .get_tag_sets import *
from .get_tenant_projects import *
from .get_tenants import *
from .get_variables import *
from .git_credential import *
from .github_repository_feed import *
from .helm_feed import *
from .library_variable_set import *
from .lifecycle import *
from .maven_feed import *
from .nuget_feed import *
from .project import *
from .project_group import *
from .provider import *
from .runbook import *
from .script_module import *
from .space import *
from .tag import *
from .tag_set import *
from .tenant import *
from .tenant_common_variable import *
from .tenant_project import *
from .tenant_project_variable import *
from .tentacle_certificate import *
from .username_password_account import *
from .variable import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_octopusdeploy.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_octopusdeploy.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "octopusdeploy",
  "mod": "index/artifactoryGenericFeed",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/artifactoryGenericFeed:ArtifactoryGenericFeed": "ArtifactoryGenericFeed"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/awsElasticContainerRegistry",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/awsElasticContainerRegistry:AwsElasticContainerRegistry": "AwsElasticContainerRegistry"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/dockerContainerRegistry",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/dockerContainerRegistry:DockerContainerRegistry": "DockerContainerRegistry"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/environment",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/environment:Environment": "Environment"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/gitCredential",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/gitCredential:GitCredential": "GitCredential"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/githubRepositoryFeed",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/githubRepositoryFeed:GithubRepositoryFeed": "GithubRepositoryFeed"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/helmFeed",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/helmFeed:HelmFeed": "HelmFeed"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/libraryVariableSet",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/libraryVariableSet:LibraryVariableSet": "LibraryVariableSet"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/lifecycle",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/lifecycle:Lifecycle": "Lifecycle"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/mavenFeed",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/mavenFeed:MavenFeed": "MavenFeed"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/nugetFeed",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/nugetFeed:NugetFeed": "NugetFeed"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/project",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/project:Project": "Project"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/projectGroup",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/projectGroup:ProjectGroup": "ProjectGroup"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/runbook",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/runbook:Runbook": "Runbook"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/scriptModule",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/scriptModule:ScriptModule": "ScriptModule"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/space",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/space:Space": "Space"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/tag",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/tag:Tag": "Tag"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/tagSet",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/tagSet:TagSet": "TagSet"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/tenant",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/tenant:Tenant": "Tenant"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/tenantCommonVariable",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/tenantCommonVariable:TenantCommonVariable": "TenantCommonVariable"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/tenantProject",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/tenantProject:TenantProject": "TenantProject"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/tenantProjectVariable",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/tenantProjectVariable:TenantProjectVariable": "TenantProjectVariable"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/tentacleCertificate",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/tentacleCertificate:TentacleCertificate": "TentacleCertificate"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/usernamePasswordAccount",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/usernamePasswordAccount:UsernamePasswordAccount": "UsernamePasswordAccount"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/variable",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/variable:Variable": "Variable"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "octopusdeploy",
  "token": "pulumi:providers:octopusdeploy",
  "fqn": "pulumi_octopusdeploy",
  "class": "Provider"
 }
]
"""
)
