# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .aws_account import *
from .aws_openid_connect_account import *
from .azure_cloud_service_deployment_target import *
from .azure_openid_connect import *
from .azure_service_fabric_cluster_deployment_target import *
from .azure_service_principal import *
from .azure_subscription_account import *
from .azure_web_app_deployment_target import *
from .certificate import *
from .channel import *
from .cloud_region_deployment_target import *
from .deployment_process import *
from .dynamic_worker_pool import *
from .external_feed_create_release_trigger import *
from .gcp_account import *
from .get_accounts import *
from .get_azure_cloud_service_deployment_targets import *
from .get_azure_service_fabric_cluster_deployment_targets import *
from .get_azure_web_app_deployment_targets import *
from .get_certificates import *
from .get_channels import *
from .get_cloud_region_deployment_targets import *
from .get_deployment_targets import *
from .get_kubernetes_agent_deployment_targets import *
from .get_kubernetes_agent_workers import *
from .get_kubernetes_cluster_deployment_targets import *
from .get_listening_tentacle_deployment_targets import *
from .get_machine import *
from .get_machine_policies import *
from .get_offline_package_drop_deployment_targets import *
from .get_polling_tentacle_deployment_targets import *
from .get_ssh_connection_deployment_targets import *
from .get_teams import *
from .get_user_roles import *
from .get_users import *
from .get_worker_pools import *
from .kubernetes_agent_deployment_target import *
from .kubernetes_agent_worker import *
from .kubernetes_cluster_deployment_target import *
from .listening_tentacle_deployment_target import *
from .machine_policy import *
from .offline_package_drop_deployment_target import *
from .polling_subscription_id import *
from .polling_tentacle_deployment_target import *
from .project_deployment_target_trigger import *
from .project_scheduled_trigger import *
from .provider import *
from .runbook_process import *
from .scoped_user_role import *
from .ssh_connection_deployment_target import *
from .ssh_key_account import *
from .static_worker_pool import *
from .team import *
from .token_account import *
from .user import *
from .user_role import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_octopusdeploy.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_octopusdeploy.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "octopusdeploy",
  "mod": "index/awsAccount",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/awsAccount:AwsAccount": "AwsAccount"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/awsOpenidConnectAccount",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/awsOpenidConnectAccount:AwsOpenidConnectAccount": "AwsOpenidConnectAccount"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/azureCloudServiceDeploymentTarget",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/azureCloudServiceDeploymentTarget:AzureCloudServiceDeploymentTarget": "AzureCloudServiceDeploymentTarget"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/azureOpenidConnect",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/azureOpenidConnect:AzureOpenidConnect": "AzureOpenidConnect"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/azureServiceFabricClusterDeploymentTarget",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/azureServiceFabricClusterDeploymentTarget:AzureServiceFabricClusterDeploymentTarget": "AzureServiceFabricClusterDeploymentTarget"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/azureServicePrincipal",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/azureServicePrincipal:AzureServicePrincipal": "AzureServicePrincipal"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/azureSubscriptionAccount",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/azureSubscriptionAccount:AzureSubscriptionAccount": "AzureSubscriptionAccount"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/azureWebAppDeploymentTarget",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/azureWebAppDeploymentTarget:AzureWebAppDeploymentTarget": "AzureWebAppDeploymentTarget"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/certificate",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/certificate:Certificate": "Certificate"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/channel",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/channel:Channel": "Channel"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/cloudRegionDeploymentTarget",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/cloudRegionDeploymentTarget:CloudRegionDeploymentTarget": "CloudRegionDeploymentTarget"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/deploymentProcess",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/deploymentProcess:DeploymentProcess": "DeploymentProcess"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/dynamicWorkerPool",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/dynamicWorkerPool:DynamicWorkerPool": "DynamicWorkerPool"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/externalFeedCreateReleaseTrigger",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/externalFeedCreateReleaseTrigger:ExternalFeedCreateReleaseTrigger": "ExternalFeedCreateReleaseTrigger"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/gcpAccount",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/gcpAccount:GcpAccount": "GcpAccount"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/kubernetesAgentDeploymentTarget",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/kubernetesAgentDeploymentTarget:KubernetesAgentDeploymentTarget": "KubernetesAgentDeploymentTarget"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/kubernetesAgentWorker",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/kubernetesAgentWorker:KubernetesAgentWorker": "KubernetesAgentWorker"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/kubernetesClusterDeploymentTarget",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/kubernetesClusterDeploymentTarget:KubernetesClusterDeploymentTarget": "KubernetesClusterDeploymentTarget"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/listeningTentacleDeploymentTarget",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/listeningTentacleDeploymentTarget:ListeningTentacleDeploymentTarget": "ListeningTentacleDeploymentTarget"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/machinePolicy",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/machinePolicy:MachinePolicy": "MachinePolicy"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/offlinePackageDropDeploymentTarget",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/offlinePackageDropDeploymentTarget:OfflinePackageDropDeploymentTarget": "OfflinePackageDropDeploymentTarget"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/pollingSubscriptionId",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/pollingSubscriptionId:PollingSubscriptionId": "PollingSubscriptionId"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/pollingTentacleDeploymentTarget",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/pollingTentacleDeploymentTarget:PollingTentacleDeploymentTarget": "PollingTentacleDeploymentTarget"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/projectDeploymentTargetTrigger",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/projectDeploymentTargetTrigger:ProjectDeploymentTargetTrigger": "ProjectDeploymentTargetTrigger"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/projectScheduledTrigger",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/projectScheduledTrigger:ProjectScheduledTrigger": "ProjectScheduledTrigger"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/runbookProcess",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/runbookProcess:RunbookProcess": "RunbookProcess"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/scopedUserRole",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/scopedUserRole:ScopedUserRole": "ScopedUserRole"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/sshConnectionDeploymentTarget",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/sshConnectionDeploymentTarget:SshConnectionDeploymentTarget": "SshConnectionDeploymentTarget"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/sshKeyAccount",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/sshKeyAccount:SshKeyAccount": "SshKeyAccount"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/staticWorkerPool",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/staticWorkerPool:StaticWorkerPool": "StaticWorkerPool"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/team",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/team:Team": "Team"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/tokenAccount",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/tokenAccount:TokenAccount": "TokenAccount"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/user",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/user:User": "User"
  }
 },
 {
  "pkg": "octopusdeploy",
  "mod": "index/userRole",
  "fqn": "pulumi_octopusdeploy",
  "classes": {
   "octopusdeploy:index/userRole:UserRole": "UserRole"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "octopusdeploy",
  "token": "pulumi:providers:octopusdeploy",
  "fqn": "pulumi_octopusdeploy",
  "class": "Provider"
 }
]
"""
)
