# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs

__all__ = [
    'GetProjectGroupsResult',
    'AwaitableGetProjectGroupsResult',
    'get_project_groups',
    'get_project_groups_output',
]

@pulumi.output_type
class GetProjectGroupsResult:
    """
    A collection of values returned by getProjectGroups.
    """
    def __init__(__self__, id=None, ids=None, partial_name=None, project_groups=None, skip=None, space_id=None, take=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if ids and not isinstance(ids, list):
            raise TypeError("Expected argument 'ids' to be a list")
        pulumi.set(__self__, "ids", ids)
        if partial_name and not isinstance(partial_name, str):
            raise TypeError("Expected argument 'partial_name' to be a str")
        pulumi.set(__self__, "partial_name", partial_name)
        if project_groups and not isinstance(project_groups, list):
            raise TypeError("Expected argument 'project_groups' to be a list")
        pulumi.set(__self__, "project_groups", project_groups)
        if skip and not isinstance(skip, int):
            raise TypeError("Expected argument 'skip' to be a int")
        pulumi.set(__self__, "skip", skip)
        if space_id and not isinstance(space_id, str):
            raise TypeError("Expected argument 'space_id' to be a str")
        pulumi.set(__self__, "space_id", space_id)
        if take and not isinstance(take, int):
            raise TypeError("Expected argument 'take' to be a int")
        pulumi.set(__self__, "take", take)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The unique ID for this resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def ids(self) -> Optional[Sequence[str]]:
        """
        A filter to search by a list of IDs.
        """
        return pulumi.get(self, "ids")

    @property
    @pulumi.getter(name="partialName")
    def partial_name(self) -> Optional[str]:
        """
        A filter to search by a partial name.
        """
        return pulumi.get(self, "partial_name")

    @property
    @pulumi.getter(name="projectGroups")
    def project_groups(self) -> Sequence['outputs.GetProjectGroupsProjectGroupResult']:
        """
        A list of project groups that match the filter(s).
        """
        return pulumi.get(self, "project_groups")

    @property
    @pulumi.getter
    def skip(self) -> Optional[int]:
        """
        A filter to specify the number of items to skip in the response.
        """
        return pulumi.get(self, "skip")

    @property
    @pulumi.getter(name="spaceId")
    def space_id(self) -> str:
        """
        The space ID associated with this project group.
        """
        return pulumi.get(self, "space_id")

    @property
    @pulumi.getter
    def take(self) -> Optional[int]:
        """
        A filter to specify the number of items to take (or return) in the response.
        """
        return pulumi.get(self, "take")


class AwaitableGetProjectGroupsResult(GetProjectGroupsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetProjectGroupsResult(
            id=self.id,
            ids=self.ids,
            partial_name=self.partial_name,
            project_groups=self.project_groups,
            skip=self.skip,
            space_id=self.space_id,
            take=self.take)


def get_project_groups(ids: Optional[Sequence[str]] = None,
                       partial_name: Optional[str] = None,
                       skip: Optional[int] = None,
                       space_id: Optional[str] = None,
                       take: Optional[int] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetProjectGroupsResult:
    """
    ## Example Usage

    ```python
    import pulumi
    import pulumi_octopusdeploy as octopusdeploy

    example = octopusdeploy.get_project_groups(ids=[
            "ProjectGroups-123",
            "ProjectGroups-321",
        ],
        partial_name="Defau",
        skip=5,
        take=100)
    ```


    :param Sequence[str] ids: A filter to search by a list of IDs.
    :param str partial_name: A filter to search by a partial name.
    :param int skip: A filter to specify the number of items to skip in the response.
    :param str space_id: The space ID associated with this project group.
    :param int take: A filter to specify the number of items to take (or return) in the response.
    """
    __args__ = dict()
    __args__['ids'] = ids
    __args__['partialName'] = partial_name
    __args__['skip'] = skip
    __args__['spaceId'] = space_id
    __args__['take'] = take
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('octopusdeploy:index/getProjectGroups:getProjectGroups', __args__, opts=opts, typ=GetProjectGroupsResult).value

    return AwaitableGetProjectGroupsResult(
        id=pulumi.get(__ret__, 'id'),
        ids=pulumi.get(__ret__, 'ids'),
        partial_name=pulumi.get(__ret__, 'partial_name'),
        project_groups=pulumi.get(__ret__, 'project_groups'),
        skip=pulumi.get(__ret__, 'skip'),
        space_id=pulumi.get(__ret__, 'space_id'),
        take=pulumi.get(__ret__, 'take'))


@_utilities.lift_output_func(get_project_groups)
def get_project_groups_output(ids: Optional[pulumi.Input[Optional[Sequence[str]]]] = None,
                              partial_name: Optional[pulumi.Input[Optional[str]]] = None,
                              skip: Optional[pulumi.Input[Optional[int]]] = None,
                              space_id: Optional[pulumi.Input[Optional[str]]] = None,
                              take: Optional[pulumi.Input[Optional[int]]] = None,
                              opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetProjectGroupsResult]:
    """
    ## Example Usage

    ```python
    import pulumi
    import pulumi_octopusdeploy as octopusdeploy

    example = octopusdeploy.get_project_groups(ids=[
            "ProjectGroups-123",
            "ProjectGroups-321",
        ],
        partial_name="Defau",
        skip=5,
        take=100)
    ```


    :param Sequence[str] ids: A filter to search by a list of IDs.
    :param str partial_name: A filter to search by a partial name.
    :param int skip: A filter to specify the number of items to skip in the response.
    :param str space_id: The space ID associated with this project group.
    :param int take: A filter to specify the number of items to take (or return) in the response.
    """
    ...
