// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class DeploymentProcessStepApplyTerraformTemplateActionGoogleCloudAccount
    {
        /// <summary>
        /// Impersonate service accounts
        /// </summary>
        public readonly bool? ImpersonateServiceAccount;
        /// <summary>
        /// This sets GOOGLE_PROJECT environment variable
        /// </summary>
        public readonly string? Project;
        /// <summary>
        /// This sets GOOGLE_REGION environment variable
        /// </summary>
        public readonly string? Region;
        /// <summary>
        /// This sets GOOGLE*IMPERSONATE*SERVICE_ACCOUNT environment variable
        /// </summary>
        public readonly string? ServiceAccountEmails;
        /// <summary>
        /// When running in a Compute Engine virtual machine, use the associated VM service account
        /// </summary>
        public readonly bool? UseVmServiceAccount;
        public readonly string? Variable;
        /// <summary>
        /// This sets GOOGLE_ZONE environment variable
        /// </summary>
        public readonly string? Zone;

        [OutputConstructor]
        private DeploymentProcessStepApplyTerraformTemplateActionGoogleCloudAccount(
            bool? impersonateServiceAccount,

            string? project,

            string? region,

            string? serviceAccountEmails,

            bool? useVmServiceAccount,

            string? variable,

            string? zone)
        {
            ImpersonateServiceAccount = impersonateServiceAccount;
            Project = project;
            Region = region;
            ServiceAccountEmails = serviceAccountEmails;
            UseVmServiceAccount = useVmServiceAccount;
            Variable = variable;
            Zone = zone;
        }
    }
}
