// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class GetKubernetesAgentWorkersKubernetesAgentWorkerResult
    {
        /// <summary>
        /// Name of the Helm release that the agent belongs to.
        /// </summary>
        public readonly string AgentHelmReleaseName;
        /// <summary>
        /// Name of the Kubernetes namespace where the agent is installed.
        /// </summary>
        public readonly string AgentKubernetesNamespace;
        /// <summary>
        /// Current Tentacle version of the agent
        /// </summary>
        public readonly string AgentTentacleVersion;
        /// <summary>
        /// Current upgrade availability status of the agent. One of 'NoUpgrades', 'UpgradeAvailable', 'UpgradeSuggested', 'UpgradeRequired'
        /// </summary>
        public readonly string AgentUpgradeStatus;
        /// <summary>
        /// Current Helm chart version of the agent.
        /// </summary>
        public readonly string AgentVersion;
        /// <summary>
        /// The communication mode used by the Kubernetes agent to communicate with Octopus Server. Currently, the only supported value is 'Polling'.
        /// </summary>
        public readonly string CommunicationMode;
        /// <summary>
        /// The unique ID for this resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Whether the Kubernetes agent is disabled. If the agent is disabled, it will not be included in any deployments.
        /// </summary>
        public readonly bool IsDisabled;
        /// <summary>
        /// Optional ID of the machine policy that the Kubernetes agent will use. If not provided the default machine policy will be used.
        /// </summary>
        public readonly string MachinePolicyId;
        /// <summary>
        /// The name of this resource.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The space ID associated with this resource.
        /// </summary>
        public readonly string SpaceId;
        /// <summary>
        /// The thumbprint of the Kubernetes agent's certificate used by server to verify the identity of the agent. This is the same thumbprint that was used when installing the agent.
        /// </summary>
        public readonly string Thumbprint;
        /// <summary>
        /// If enabled the Kubernetes agent will not automatically upgrade and will stay on the currently installed version, even if the associated machine policy is configured to automatically upgrade.
        /// </summary>
        public readonly bool UpgradeLocked;
        /// <summary>
        /// The URI of the Kubernetes agent's used by the server to queue messages. This is the same subscription uri that was used when installing the agent.
        /// </summary>
        public readonly string Uri;
        /// <summary>
        /// A list of worker pool Ids specifying the pools in which this worker belongs
        /// </summary>
        public readonly ImmutableArray<string> WorkerPoolIds;

        [OutputConstructor]
        private GetKubernetesAgentWorkersKubernetesAgentWorkerResult(
            string agentHelmReleaseName,

            string agentKubernetesNamespace,

            string agentTentacleVersion,

            string agentUpgradeStatus,

            string agentVersion,

            string communicationMode,

            string id,

            bool isDisabled,

            string machinePolicyId,

            string name,

            string spaceId,

            string thumbprint,

            bool upgradeLocked,

            string uri,

            ImmutableArray<string> workerPoolIds)
        {
            AgentHelmReleaseName = agentHelmReleaseName;
            AgentKubernetesNamespace = agentKubernetesNamespace;
            AgentTentacleVersion = agentTentacleVersion;
            AgentUpgradeStatus = agentUpgradeStatus;
            AgentVersion = agentVersion;
            CommunicationMode = communicationMode;
            Id = id;
            IsDisabled = isDisabled;
            MachinePolicyId = machinePolicyId;
            Name = name;
            SpaceId = spaceId;
            Thumbprint = thumbprint;
            UpgradeLocked = upgradeLocked;
            Uri = uri;
            WorkerPoolIds = workerPoolIds;
        }
    }
}
