// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetResult
    {
        public readonly ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetAuthenticationResult> Authentications;
        public readonly ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetAwsAccountAuthenticationResult> AwsAccountAuthentications;
        public readonly ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetAzureServicePrincipalAuthenticationResult> AzureServicePrincipalAuthentications;
        public readonly ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetCertificateAuthenticationResult> CertificateAuthentications;
        public readonly string ClusterCertificate;
        public readonly string ClusterCertificatePath;
        public readonly string ClusterUrl;
        public readonly string ContainerOptions;
        public readonly ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetContainerResult> Containers;
        public readonly string DefaultWorkerPoolId;
        public readonly ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetEndpointResult> Endpoints;
        /// <summary>
        /// A list of environment IDs associated with this resource.
        /// </summary>
        public readonly ImmutableArray<string> Environments;
        public readonly ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetGcpAccountAuthenticationResult> GcpAccountAuthentications;
        public readonly bool HasLatestCalamari;
        /// <summary>
        /// Represents the health status of this deployment target. Valid health statuses are `HasWarnings`, `Healthy`, `Unavailable`, `Unhealthy`, or `Unknown`.
        /// </summary>
        public readonly string HealthStatus;
        /// <summary>
        /// The unique ID for this resource.
        /// </summary>
        public readonly string Id;
        public readonly bool IsDisabled;
        public readonly bool IsInProcess;
        public readonly string MachinePolicyId;
        /// <summary>
        /// The name of this resource.
        /// </summary>
        public readonly string Name;
        public readonly string Namespace;
        public readonly string OperatingSystem;
        public readonly ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetPodAuthenticationResult> PodAuthentications;
        public readonly string ProxyId;
        public readonly ImmutableArray<string> Roles;
        public readonly bool RunningInContainer;
        public readonly string ShellName;
        public readonly string ShellVersion;
        public readonly bool SkipTlsVerification;
        /// <summary>
        /// The space ID associated with this resource.
        /// </summary>
        public readonly string SpaceId;
        /// <summary>
        /// The status of this resource. Valid statuses are `CalamariNeedsUpgrade`, `Disabled`, `NeedsUpgrade`, `Offline`, `Online`, or `Unknown`.
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// A summary elaborating on the status of this resource.
        /// </summary>
        public readonly string StatusSummary;
        /// <summary>
        /// A list of tenant tags associated with this resource.
        /// </summary>
        public readonly ImmutableArray<string> TenantTags;
        /// <summary>
        /// The tenanted deployment mode of the resource. Valid account types are `Untenanted`, `TenantedOrUntenanted`, or `Tenanted`.
        /// </summary>
        public readonly string TenantedDeploymentParticipation;
        /// <summary>
        /// A list of tenant IDs associated with this resource.
        /// </summary>
        public readonly ImmutableArray<string> Tenants;
        public readonly string Thumbprint;
        public readonly string Uri;

        [OutputConstructor]
        private GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetResult(
            ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetAuthenticationResult> authentications,

            ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetAwsAccountAuthenticationResult> awsAccountAuthentications,

            ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetAzureServicePrincipalAuthenticationResult> azureServicePrincipalAuthentications,

            ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetCertificateAuthenticationResult> certificateAuthentications,

            string clusterCertificate,

            string clusterCertificatePath,

            string clusterUrl,

            string containerOptions,

            ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetContainerResult> containers,

            string defaultWorkerPoolId,

            ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetEndpointResult> endpoints,

            ImmutableArray<string> environments,

            ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetGcpAccountAuthenticationResult> gcpAccountAuthentications,

            bool hasLatestCalamari,

            string healthStatus,

            string id,

            bool isDisabled,

            bool isInProcess,

            string machinePolicyId,

            string name,

            string @namespace,

            string operatingSystem,

            ImmutableArray<Outputs.GetKubernetesClusterDeploymentTargetsKubernetesClusterDeploymentTargetPodAuthenticationResult> podAuthentications,

            string proxyId,

            ImmutableArray<string> roles,

            bool runningInContainer,

            string shellName,

            string shellVersion,

            bool skipTlsVerification,

            string spaceId,

            string status,

            string statusSummary,

            ImmutableArray<string> tenantTags,

            string tenantedDeploymentParticipation,

            ImmutableArray<string> tenants,

            string thumbprint,

            string uri)
        {
            Authentications = authentications;
            AwsAccountAuthentications = awsAccountAuthentications;
            AzureServicePrincipalAuthentications = azureServicePrincipalAuthentications;
            CertificateAuthentications = certificateAuthentications;
            ClusterCertificate = clusterCertificate;
            ClusterCertificatePath = clusterCertificatePath;
            ClusterUrl = clusterUrl;
            ContainerOptions = containerOptions;
            Containers = containers;
            DefaultWorkerPoolId = defaultWorkerPoolId;
            Endpoints = endpoints;
            Environments = environments;
            GcpAccountAuthentications = gcpAccountAuthentications;
            HasLatestCalamari = hasLatestCalamari;
            HealthStatus = healthStatus;
            Id = id;
            IsDisabled = isDisabled;
            IsInProcess = isInProcess;
            MachinePolicyId = machinePolicyId;
            Name = name;
            Namespace = @namespace;
            OperatingSystem = operatingSystem;
            PodAuthentications = podAuthentications;
            ProxyId = proxyId;
            Roles = roles;
            RunningInContainer = runningInContainer;
            ShellName = shellName;
            ShellVersion = shellVersion;
            SkipTlsVerification = skipTlsVerification;
            SpaceId = spaceId;
            Status = status;
            StatusSummary = statusSummary;
            TenantTags = tenantTags;
            TenantedDeploymentParticipation = tenantedDeploymentParticipation;
            Tenants = tenants;
            Thumbprint = thumbprint;
            Uri = uri;
        }
    }
}
