// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class GetProjectsProjectVersioningStrategyResult
    {
        /// <summary>
        /// The ID of the step containing the donor package.
        /// </summary>
        public readonly string DonorPackageStepId;
        public readonly ImmutableArray<Outputs.GetProjectsProjectVersioningStrategyDonorPackageResult> DonorPackages;
        /// <summary>
        /// The template to use for version numbers.
        /// </summary>
        public readonly string Template;

        [OutputConstructor]
        private GetProjectsProjectVersioningStrategyResult(
            string donorPackageStepId,

            ImmutableArray<Outputs.GetProjectsProjectVersioningStrategyDonorPackageResult> donorPackages,

            string template)
        {
            DonorPackageStepId = donorPackageStepId;
            DonorPackages = donorPackages;
            Template = template;
        }
    }
}
