// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class GetProjectsProjectTemplateResult
    {
        /// <summary>
        /// The default value for the parameter.
        /// </summary>
        public readonly string DefaultValue;
        /// <summary>
        /// The display settings for the parameter.
        /// </summary>
        public readonly ImmutableDictionary<string, string> DisplaySettings;
        /// <summary>
        /// The help text for the parameter.
        /// </summary>
        public readonly string HelpText;
        /// <summary>
        /// The ID of the template parameter.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The label shown beside the parameter.
        /// </summary>
        public readonly string Label;
        /// <summary>
        /// The name of the variable set by the parameter.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetProjectsProjectTemplateResult(
            string defaultValue,

            ImmutableDictionary<string, string> displaySettings,

            string helpText,

            string id,

            string label,

            string name)
        {
            DefaultValue = defaultValue;
            DisplaySettings = displaySettings;
            HelpText = helpText;
            Id = id;
            Label = label;
            Name = name;
        }
    }
}
