// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class ProjectScheduledTriggerCronExpressionSchedule
    {
        /// <summary>
        /// The cron expression for the schedule.
        /// </summary>
        public readonly string CronExpression;

        [OutputConstructor]
        private ProjectScheduledTriggerCronExpressionSchedule(string cronExpression)
        {
            CronExpression = cronExpression;
        }
    }
}
