// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class ProjectScheduledTriggerOnceDailySchedule
    {
        /// <summary>
        /// The days of the week to run the trigger.
        /// </summary>
        public readonly ImmutableArray<string> DaysOfWeeks;
        /// <summary>
        /// The time of day to start the trigger.
        /// </summary>
        public readonly string StartTime;

        [OutputConstructor]
        private ProjectScheduledTriggerOnceDailySchedule(
            ImmutableArray<string> daysOfWeeks,

            string startTime)
        {
            DaysOfWeeks = daysOfWeeks;
            StartTime = startTime;
        }
    }
}
