// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class RunbookProcessStepDeployKubernetesSecretAction
    {
        /// <summary>
        /// Represents the template that is associated with this action.
        /// </summary>
        public readonly Outputs.RunbookProcessStepDeployKubernetesSecretActionActionTemplate? ActionTemplate;
        public readonly bool? CanBeUsedForProjectVersioning;
        /// <summary>
        /// The channels associated with this deployment action.
        /// </summary>
        public readonly ImmutableArray<string> Channels;
        /// <summary>
        /// The condition associated with this deployment action.
        /// </summary>
        public readonly string? Condition;
        /// <summary>
        /// The deployment action container associated with this deployment action.
        /// </summary>
        public readonly ImmutableArray<Outputs.RunbookProcessStepDeployKubernetesSecretActionContainer> Containers;
        /// <summary>
        /// The environments within which this deployment action will run.
        /// </summary>
        public readonly ImmutableArray<string> Environments;
        /// <summary>
        /// The environments that this step will be skipped in
        /// </summary>
        public readonly ImmutableArray<string> ExcludedEnvironments;
        /// <summary>
        /// A list of enabled features for this action.
        /// </summary>
        public readonly ImmutableArray<string> Features;
        /// <summary>
        /// Configuration for resource sourcing from a git repository.
        /// </summary>
        public readonly Outputs.RunbookProcessStepDeployKubernetesSecretActionGitDependency? GitDependency;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// Indicates the disabled status of this deployment action.
        /// </summary>
        public readonly bool? IsDisabled;
        /// <summary>
        /// Indicates the required status of this deployment action.
        /// </summary>
        public readonly bool? IsRequired;
        /// <summary>
        /// Indicates the status of the Kubernetes Object Status feature
        /// </summary>
        public readonly bool? KubernetesObjectStatusCheckEnabled;
        /// <summary>
        /// The name of this resource.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The notes associated with this deployment action.
        /// </summary>
        public readonly string? Notes;
        /// <summary>
        /// The package assocated with this action.
        /// </summary>
        public readonly ImmutableArray<Outputs.RunbookProcessStepDeployKubernetesSecretActionPackage> Packages;
        /// <summary>
        /// A list of properties associated with this package.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Properties;
        /// <summary>
        /// Whether this step runs on a worker or on the target
        /// </summary>
        public readonly bool? RunOnServer;
        /// <summary>
        /// The name of the secret resource
        /// </summary>
        public readonly string SecretName;
        public readonly ImmutableDictionary<string, string> SecretValues;
        /// <summary>
        /// The human-readable unique identifier for this resource.
        /// </summary>
        public readonly string? Slug;
        public readonly int? SortOrder;
        /// <summary>
        /// A list of tenant tags associated with this resource.
        /// </summary>
        public readonly ImmutableArray<string> TenantTags;
        /// <summary>
        /// The worker pool associated with this deployment action.
        /// </summary>
        public readonly string? WorkerPoolId;
        /// <summary>
        /// The worker pool variable associated with this deployment action.
        /// </summary>
        public readonly string? WorkerPoolVariable;

        [OutputConstructor]
        private RunbookProcessStepDeployKubernetesSecretAction(
            Outputs.RunbookProcessStepDeployKubernetesSecretActionActionTemplate? actionTemplate,

            bool? canBeUsedForProjectVersioning,

            ImmutableArray<string> channels,

            string? condition,

            ImmutableArray<Outputs.RunbookProcessStepDeployKubernetesSecretActionContainer> containers,

            ImmutableArray<string> environments,

            ImmutableArray<string> excludedEnvironments,

            ImmutableArray<string> features,

            Outputs.RunbookProcessStepDeployKubernetesSecretActionGitDependency? gitDependency,

            string? id,

            bool? isDisabled,

            bool? isRequired,

            bool? kubernetesObjectStatusCheckEnabled,

            string name,

            string? notes,

            ImmutableArray<Outputs.RunbookProcessStepDeployKubernetesSecretActionPackage> packages,

            ImmutableDictionary<string, string>? properties,

            bool? runOnServer,

            string secretName,

            ImmutableDictionary<string, string> secretValues,

            string? slug,

            int? sortOrder,

            ImmutableArray<string> tenantTags,

            string? workerPoolId,

            string? workerPoolVariable)
        {
            ActionTemplate = actionTemplate;
            CanBeUsedForProjectVersioning = canBeUsedForProjectVersioning;
            Channels = channels;
            Condition = condition;
            Containers = containers;
            Environments = environments;
            ExcludedEnvironments = excludedEnvironments;
            Features = features;
            GitDependency = gitDependency;
            Id = id;
            IsDisabled = isDisabled;
            IsRequired = isRequired;
            KubernetesObjectStatusCheckEnabled = kubernetesObjectStatusCheckEnabled;
            Name = name;
            Notes = notes;
            Packages = packages;
            Properties = properties;
            RunOnServer = runOnServer;
            SecretName = secretName;
            SecretValues = secretValues;
            Slug = slug;
            SortOrder = sortOrder;
            TenantTags = tenantTags;
            WorkerPoolId = workerPoolId;
            WorkerPoolVariable = workerPoolVariable;
        }
    }
}
