// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Inputs
{

    public sealed class GetVariablesScopeArgs : global::Pulumi.InvokeArgs
    {
        [Input("actions")]
        private List<string>? _actions;

        /// <summary>
        /// A list of actions that are scoped to this variable value.
        /// </summary>
        public List<string> Actions
        {
            get => _actions ?? (_actions = new List<string>());
            set => _actions = value;
        }

        [Input("channels")]
        private List<string>? _channels;

        /// <summary>
        /// A list of channels that are scoped to this variable value.
        /// </summary>
        public List<string> Channels
        {
            get => _channels ?? (_channels = new List<string>());
            set => _channels = value;
        }

        [Input("environments")]
        private List<string>? _environments;

        /// <summary>
        /// A list of environments that are scoped to this variable value.
        /// </summary>
        public List<string> Environments
        {
            get => _environments ?? (_environments = new List<string>());
            set => _environments = value;
        }

        [Input("machines")]
        private List<string>? _machines;

        /// <summary>
        /// A list of machines that are scoped to this variable value.
        /// </summary>
        public List<string> Machines
        {
            get => _machines ?? (_machines = new List<string>());
            set => _machines = value;
        }

        [Input("processes")]
        private List<string>? _processes;

        /// <summary>
        /// A list of processes that are scoped to this variable value.
        /// </summary>
        public List<string> Processes
        {
            get => _processes ?? (_processes = new List<string>());
            set => _processes = value;
        }

        [Input("roles")]
        private List<string>? _roles;

        /// <summary>
        /// A list of roles that are scoped to this variable value.
        /// </summary>
        public List<string> Roles
        {
            get => _roles ?? (_roles = new List<string>());
            set => _roles = value;
        }

        [Input("tenantTags")]
        private List<string>? _tenantTags;

        /// <summary>
        /// A list of tenant tags that are scoped to this variable value.
        /// </summary>
        public List<string> TenantTags
        {
            get => _tenantTags ?? (_tenantTags = new List<string>());
            set => _tenantTags = value;
        }

        public GetVariablesScopeArgs()
        {
        }
        public static new GetVariablesScopeArgs Empty => new GetVariablesScopeArgs();
    }
}
