// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Inputs
{

    public sealed class KubernetesClusterDeploymentTargetPodAuthenticationArgs : global::Pulumi.ResourceArgs
    {
        [Input("tokenPath", required: true)]
        public Input<string> TokenPath { get; set; } = null!;

        public KubernetesClusterDeploymentTargetPodAuthenticationArgs()
        {
        }
        public static new KubernetesClusterDeploymentTargetPodAuthenticationArgs Empty => new KubernetesClusterDeploymentTargetPodAuthenticationArgs();
    }
}
