// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Inputs
{

    public sealed class ProjectScheduledTriggerCronExpressionScheduleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The cron expression for the schedule.
        /// </summary>
        [Input("cronExpression", required: true)]
        public Input<string> CronExpression { get; set; } = null!;

        public ProjectScheduledTriggerCronExpressionScheduleArgs()
        {
        }
        public static new ProjectScheduledTriggerCronExpressionScheduleArgs Empty => new ProjectScheduledTriggerCronExpressionScheduleArgs();
    }
}
