// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Inputs
{

    public sealed class ProjectScheduledTriggerContinuousDailyScheduleArgs : global::Pulumi.ResourceArgs
    {
        [Input("daysOfWeeks", required: true)]
        private InputList<string>? _daysOfWeeks;

        /// <summary>
        /// The days of the week to run the trigger.
        /// </summary>
        public InputList<string> DaysOfWeeks
        {
            get => _daysOfWeeks ?? (_daysOfWeeks = new InputList<string>());
            set => _daysOfWeeks = value;
        }

        /// <summary>
        /// How often to run the trigger in hours. Only used when the interval is set to 'OnceHourly'.
        /// </summary>
        [Input("hourInterval")]
        public Input<int>? HourInterval { get; set; }

        /// <summary>
        /// The interval in minutes to run the trigger.
        /// </summary>
        [Input("interval", required: true)]
        public Input<string> Interval { get; set; } = null!;

        /// <summary>
        /// How often to run the trigger in minutes. Only used when the interval is set to 'OnceEveryMinute'.
        /// </summary>
        [Input("minuteInterval")]
        public Input<int>? MinuteInterval { get; set; }

        /// <summary>
        /// The time of day to start the trigger.
        /// </summary>
        [Input("runAfter", required: true)]
        public Input<string> RunAfter { get; set; } = null!;

        /// <summary>
        /// The time of day to end the trigger.
        /// </summary>
        [Input("runUntil", required: true)]
        public Input<string> RunUntil { get; set; } = null!;

        public ProjectScheduledTriggerContinuousDailyScheduleArgs()
        {
        }
        public static new ProjectScheduledTriggerContinuousDailyScheduleArgs Empty => new ProjectScheduledTriggerContinuousDailyScheduleArgs();
    }
}
