// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this data source to retrieve information about Git credentials in Octopus Deploy.
 */
export function getGitCredentials(args?: GetGitCredentialsArgs, opts?: pulumi.InvokeOptions): Promise<GetGitCredentialsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("octopusdeploy:index/getGitCredentials:getGitCredentials", {
        "name": args.name,
        "skip": args.skip,
        "spaceId": args.spaceId,
        "take": args.take,
    }, opts);
}

/**
 * A collection of arguments for invoking getGitCredentials.
 */
export interface GetGitCredentialsArgs {
    /**
     * The name of the Git Credential to filter by.
     */
    name?: string;
    /**
     * The number of records to skip.
     */
    skip?: number;
    /**
     * The space ID associated with this Git Credential.
     */
    spaceId?: string;
    /**
     * The number of records to take.
     */
    take?: number;
}

/**
 * A collection of values returned by getGitCredentials.
 */
export interface GetGitCredentialsResult {
    /**
     * Provides information about existing GitCredentials.
     */
    readonly gitCredentials: outputs.GetGitCredentialsGitCredential[];
    /**
     * The unique ID for this resource.
     */
    readonly id: string;
    /**
     * The name of the Git Credential to filter by.
     */
    readonly name?: string;
    /**
     * The number of records to skip.
     */
    readonly skip?: number;
    /**
     * The space ID associated with this Git Credential.
     */
    readonly spaceId?: string;
    /**
     * The number of records to take.
     */
    readonly take?: number;
}
/**
 * Use this data source to retrieve information about Git credentials in Octopus Deploy.
 */
export function getGitCredentialsOutput(args?: GetGitCredentialsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetGitCredentialsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("octopusdeploy:index/getGitCredentials:getGitCredentials", {
        "name": args.name,
        "skip": args.skip,
        "spaceId": args.spaceId,
        "take": args.take,
    }, opts);
}

/**
 * A collection of arguments for invoking getGitCredentials.
 */
export interface GetGitCredentialsOutputArgs {
    /**
     * The name of the Git Credential to filter by.
     */
    name?: pulumi.Input<string>;
    /**
     * The number of records to skip.
     */
    skip?: pulumi.Input<number>;
    /**
     * The space ID associated with this Git Credential.
     */
    spaceId?: pulumi.Input<string>;
    /**
     * The number of records to take.
     */
    take?: pulumi.Input<number>;
}
