// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides information about existing lifecycles.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as octopusdeploy from "@pulumi/octopusdeploy";
 *
 * const example = octopusdeploy.getLifecycles({
 *     ids: [
 *         "Lifecycles-123",
 *         "Lifecycles-321",
 *     ],
 *     partialName: "Defau",
 *     skip: 5,
 *     take: 100,
 * });
 * ```
 */
export function getLifecycles(args?: GetLifecyclesArgs, opts?: pulumi.InvokeOptions): Promise<GetLifecyclesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("octopusdeploy:index/getLifecycles:getLifecycles", {
        "ids": args.ids,
        "partialName": args.partialName,
        "skip": args.skip,
        "spaceId": args.spaceId,
        "take": args.take,
    }, opts);
}

/**
 * A collection of arguments for invoking getLifecycles.
 */
export interface GetLifecyclesArgs {
    /**
     * A list of lifecycle IDs to filter by.
     */
    ids?: string[];
    /**
     * A partial name to filter lifecycles by.
     */
    partialName?: string;
    /**
     * A filter to specify the number of items to skip in the response.
     */
    skip?: number;
    /**
     * The space ID associated with this lifecycle.
     */
    spaceId?: string;
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    take?: number;
}

/**
 * A collection of values returned by getLifecycles.
 */
export interface GetLifecyclesResult {
    /**
     * The ID of the lifecycle.
     */
    readonly id: string;
    /**
     * A list of lifecycle IDs to filter by.
     */
    readonly ids?: string[];
    readonly lifecycles: outputs.GetLifecyclesLifecycle[];
    /**
     * A partial name to filter lifecycles by.
     */
    readonly partialName?: string;
    /**
     * A filter to specify the number of items to skip in the response.
     */
    readonly skip?: number;
    /**
     * The space ID associated with this lifecycle.
     */
    readonly spaceId?: string;
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    readonly take?: number;
}
/**
 * Provides information about existing lifecycles.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as octopusdeploy from "@pulumi/octopusdeploy";
 *
 * const example = octopusdeploy.getLifecycles({
 *     ids: [
 *         "Lifecycles-123",
 *         "Lifecycles-321",
 *     ],
 *     partialName: "Defau",
 *     skip: 5,
 *     take: 100,
 * });
 * ```
 */
export function getLifecyclesOutput(args?: GetLifecyclesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetLifecyclesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("octopusdeploy:index/getLifecycles:getLifecycles", {
        "ids": args.ids,
        "partialName": args.partialName,
        "skip": args.skip,
        "spaceId": args.spaceId,
        "take": args.take,
    }, opts);
}

/**
 * A collection of arguments for invoking getLifecycles.
 */
export interface GetLifecyclesOutputArgs {
    /**
     * A list of lifecycle IDs to filter by.
     */
    ids?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A partial name to filter lifecycles by.
     */
    partialName?: pulumi.Input<string>;
    /**
     * A filter to specify the number of items to skip in the response.
     */
    skip?: pulumi.Input<number>;
    /**
     * The space ID associated with this lifecycle.
     */
    spaceId?: pulumi.Input<string>;
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    take?: pulumi.Input<number>;
}
