// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as octopusdeploy from "@pulumi/octopusdeploy";
 *
 * const example = octopusdeploy.getProjectGroups({
 *     ids: [
 *         "ProjectGroups-123",
 *         "ProjectGroups-321",
 *     ],
 *     partialName: "Defau",
 *     skip: 5,
 *     take: 100,
 * });
 * ```
 */
export function getProjectGroups(args?: GetProjectGroupsArgs, opts?: pulumi.InvokeOptions): Promise<GetProjectGroupsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("octopusdeploy:index/getProjectGroups:getProjectGroups", {
        "ids": args.ids,
        "partialName": args.partialName,
        "skip": args.skip,
        "spaceId": args.spaceId,
        "take": args.take,
    }, opts);
}

/**
 * A collection of arguments for invoking getProjectGroups.
 */
export interface GetProjectGroupsArgs {
    /**
     * A filter to search by a list of IDs.
     */
    ids?: string[];
    /**
     * A filter to search by a partial name.
     */
    partialName?: string;
    /**
     * A filter to specify the number of items to skip in the response.
     */
    skip?: number;
    /**
     * The space ID associated with this project group.
     */
    spaceId?: string;
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    take?: number;
}

/**
 * A collection of values returned by getProjectGroups.
 */
export interface GetProjectGroupsResult {
    /**
     * The unique ID for this resource.
     */
    readonly id: string;
    /**
     * A filter to search by a list of IDs.
     */
    readonly ids?: string[];
    /**
     * A filter to search by a partial name.
     */
    readonly partialName?: string;
    /**
     * A list of project groups that match the filter(s).
     */
    readonly projectGroups: outputs.GetProjectGroupsProjectGroup[];
    /**
     * A filter to specify the number of items to skip in the response.
     */
    readonly skip?: number;
    /**
     * The space ID associated with this project group.
     */
    readonly spaceId: string;
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    readonly take?: number;
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as octopusdeploy from "@pulumi/octopusdeploy";
 *
 * const example = octopusdeploy.getProjectGroups({
 *     ids: [
 *         "ProjectGroups-123",
 *         "ProjectGroups-321",
 *     ],
 *     partialName: "Defau",
 *     skip: 5,
 *     take: 100,
 * });
 * ```
 */
export function getProjectGroupsOutput(args?: GetProjectGroupsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetProjectGroupsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("octopusdeploy:index/getProjectGroups:getProjectGroups", {
        "ids": args.ids,
        "partialName": args.partialName,
        "skip": args.skip,
        "spaceId": args.spaceId,
        "take": args.take,
    }, opts);
}

/**
 * A collection of arguments for invoking getProjectGroups.
 */
export interface GetProjectGroupsOutputArgs {
    /**
     * A filter to search by a list of IDs.
     */
    ids?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A filter to search by a partial name.
     */
    partialName?: pulumi.Input<string>;
    /**
     * A filter to specify the number of items to skip in the response.
     */
    skip?: pulumi.Input<number>;
    /**
     * The space ID associated with this project group.
     */
    spaceId?: pulumi.Input<string>;
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    take?: pulumi.Input<number>;
}
