// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as octopusdeploy from "@pulumi/octopusdeploy";
 *
 * const spaces = octopusdeploy.getSpaces({
 *     ids: [
 *         "Spaces-123",
 *         "Spaces-321",
 *     ],
 *     partialName: "Defau",
 *     skip: 5,
 *     take: 100,
 * });
 * ```
 */
export function getSpaces(args?: GetSpacesArgs, opts?: pulumi.InvokeOptions): Promise<GetSpacesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("octopusdeploy:index/getSpaces:getSpaces", {
        "ids": args.ids,
        "partialName": args.partialName,
        "skip": args.skip,
        "take": args.take,
    }, opts);
}

/**
 * A collection of arguments for invoking getSpaces.
 */
export interface GetSpacesArgs {
    /**
     * A filter to search by a list of IDs.
     */
    ids?: string[];
    /**
     * A filter to search by a partial name.
     */
    partialName?: string;
    /**
     * A filter to specify the number of items to skip in the response.
     */
    skip?: number;
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    take?: number;
}

/**
 * A collection of values returned by getSpaces.
 */
export interface GetSpacesResult {
    /**
     * The unique ID for this resource.
     */
    readonly id: string;
    /**
     * A filter to search by a list of IDs.
     */
    readonly ids?: string[];
    /**
     * A filter to search by a partial name.
     */
    readonly partialName?: string;
    /**
     * A filter to specify the number of items to skip in the response.
     */
    readonly skip?: number;
    readonly spaces: outputs.GetSpacesSpace[];
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    readonly take?: number;
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as octopusdeploy from "@pulumi/octopusdeploy";
 *
 * const spaces = octopusdeploy.getSpaces({
 *     ids: [
 *         "Spaces-123",
 *         "Spaces-321",
 *     ],
 *     partialName: "Defau",
 *     skip: 5,
 *     take: 100,
 * });
 * ```
 */
export function getSpacesOutput(args?: GetSpacesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSpacesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("octopusdeploy:index/getSpaces:getSpaces", {
        "ids": args.ids,
        "partialName": args.partialName,
        "skip": args.skip,
        "take": args.take,
    }, opts);
}

/**
 * A collection of arguments for invoking getSpaces.
 */
export interface GetSpacesOutputArgs {
    /**
     * A filter to search by a list of IDs.
     */
    ids?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A filter to search by a partial name.
     */
    partialName?: pulumi.Input<string>;
    /**
     * A filter to specify the number of items to skip in the response.
     */
    skip?: pulumi.Input<number>;
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    take?: pulumi.Input<number>;
}
