// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides information about existing tenants.
 */
export function getTenants(args?: GetTenantsArgs, opts?: pulumi.InvokeOptions): Promise<GetTenantsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("octopusdeploy:index/getTenants:getTenants", {
        "clonedFromTenantId": args.clonedFromTenantId,
        "ids": args.ids,
        "isClone": args.isClone,
        "name": args.name,
        "partialName": args.partialName,
        "projectId": args.projectId,
        "skip": args.skip,
        "spaceId": args.spaceId,
        "tags": args.tags,
        "take": args.take,
    }, opts);
}

/**
 * A collection of arguments for invoking getTenants.
 */
export interface GetTenantsArgs {
    /**
     * A filter to search for a cloned tenant by its ID.
     */
    clonedFromTenantId?: string;
    /**
     * A filter to search by a list of IDs.
     */
    ids?: string[];
    /**
     * A filter to search for cloned resources.
     */
    isClone?: boolean;
    /**
     * A filter to search by name.
     */
    name?: string;
    /**
     * A filter to search by a partial name.
     */
    partialName?: string;
    /**
     * A filter to search by a project ID.
     */
    projectId?: string;
    /**
     * A filter to specify the number of items to skip in the response.
     */
    skip?: number;
    /**
     * The space ID associated with this tenants.
     */
    spaceId?: string;
    /**
     * A filter to search by a list of tags.
     */
    tags?: string[];
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    take?: number;
}

/**
 * A collection of values returned by getTenants.
 */
export interface GetTenantsResult {
    /**
     * A filter to search for a cloned tenant by its ID.
     */
    readonly clonedFromTenantId?: string;
    /**
     * The unique ID for this resource.
     */
    readonly id: string;
    /**
     * A filter to search by a list of IDs.
     */
    readonly ids?: string[];
    /**
     * A filter to search for cloned resources.
     */
    readonly isClone?: boolean;
    /**
     * A filter to search by name.
     */
    readonly name?: string;
    /**
     * A filter to search by a partial name.
     */
    readonly partialName?: string;
    /**
     * A filter to search by a project ID.
     */
    readonly projectId?: string;
    /**
     * A filter to specify the number of items to skip in the response.
     */
    readonly skip?: number;
    /**
     * The space ID associated with this tenants.
     */
    readonly spaceId: string;
    /**
     * A filter to search by a list of tags.
     */
    readonly tags?: string[];
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    readonly take?: number;
    readonly tenants: outputs.GetTenantsTenant[];
}
/**
 * Provides information about existing tenants.
 */
export function getTenantsOutput(args?: GetTenantsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetTenantsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("octopusdeploy:index/getTenants:getTenants", {
        "clonedFromTenantId": args.clonedFromTenantId,
        "ids": args.ids,
        "isClone": args.isClone,
        "name": args.name,
        "partialName": args.partialName,
        "projectId": args.projectId,
        "skip": args.skip,
        "spaceId": args.spaceId,
        "tags": args.tags,
        "take": args.take,
    }, opts);
}

/**
 * A collection of arguments for invoking getTenants.
 */
export interface GetTenantsOutputArgs {
    /**
     * A filter to search for a cloned tenant by its ID.
     */
    clonedFromTenantId?: pulumi.Input<string>;
    /**
     * A filter to search by a list of IDs.
     */
    ids?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A filter to search for cloned resources.
     */
    isClone?: pulumi.Input<boolean>;
    /**
     * A filter to search by name.
     */
    name?: pulumi.Input<string>;
    /**
     * A filter to search by a partial name.
     */
    partialName?: pulumi.Input<string>;
    /**
     * A filter to search by a project ID.
     */
    projectId?: pulumi.Input<string>;
    /**
     * A filter to specify the number of items to skip in the response.
     */
    skip?: pulumi.Input<number>;
    /**
     * The space ID associated with this tenants.
     */
    spaceId?: pulumi.Input<string>;
    /**
     * A filter to search by a list of tags.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    take?: pulumi.Input<number>;
}
